version: '3'

services:
  mysql:
    image: mysql:5
    platform: linux/amd64
    container_name: mysql
    volumes:
      - ./.mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "root"
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-proot" ]
      timeout: 10s
      retries: 10

  sequelize-cli:
    container_name: sequelize-cli
    build: ..
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_URI: "mysql://root:root@mysql:3306/root"
    entrypoint: npm run db
